import type{Rng}from"@/lib/rng"; import type{Die,Face,Fighter,ForgeRound,Offer,RollResult}from"./types";
const BASE:Die=[{kind:"damage",value:1},{kind:"damage",value:1},{kind:"shield",value:1},{kind:"shield",value:1},{kind:"energy",value:1},{kind:"wild",value:1}];
export const createFighter=():Fighter=>({health:30,shield:0,coins:0,discount:0,dice:[0,1,2].map(()=>BASE.map(f=>({...f})))});
export const rollDice=(d:Die[],r:Rng)=>d.map(x=>r.int(0,x.length-1));
export function shownFaces(d:Die[],roll:number[]):Face[]{const raw=roll.map((x,i)=>d[i][x]);const best=raw.filter(f=>f.kind!=="wild").sort((a,b)=>b.value-a.value)[0]??{kind:"damage",value:1};return raw.map(f=>f.kind==="wild"?{...best}:{...f});}
export function scoreRoll(f:Face[]):RollResult{const sum=(k:Face["kind"])=>f.filter(x=>x.kind===k).reduce((n,x)=>n+x.value,0);let damage=sum("damage"),shield=sum("shield");const energy=sum("energy"),k=new Set(f.map(x=>x.kind));if(f.every(x=>x.kind==="damage"))damage=Math.ceil(damage*1.5);if(f.every(x=>x.kind==="shield"))shield+=2;return{faces:f,damage,shield,energy,discount:k.has("damage")&&k.has("shield")&&k.has("energy")?1:0};}
export function resolveCombat(p:Fighter,a:Fighter,pr:RollResult,ar:RollResult):[Fighter,Fighter]{const hit=(t:Fighter,d:number)=>{const z=Math.min(t.shield,d);return{...t,shield:t.shield-z,health:Math.max(0,t.health-d+z)}};let np=hit({...p,shield:p.shield+pr.shield},ar.damage),na=hit({...a,shield:a.shield+ar.shield},pr.damage);np={...np,coins:np.coins+2+pr.energy,discount:np.discount+pr.discount};na={...na,coins:na.coins+2+ar.energy,discount:na.discount+ar.discount};return[np,na];}
export function createShop(r:Rng,n:number):Offer[]{const p=[{face:{kind:"damage",value:2},cost:2},{face:{kind:"shield",value:2},cost:2},{face:{kind:"energy",value:2},cost:3},{face:{kind:"damage",value:3},cost:4},{face:{kind:"shield",value:3},cost:4},{face:{kind:"wild",value:1},cost:5}] satisfies Omit<Offer,"id">[];return r.shuffle(p).slice(0,3).map((o,i)=>({...o,id:`${n}-${i}`}));}
export function buyUpgrade(x:Fighter,o:Offer,d:number,f:number):Fighter|null{const price=Math.max(0,o.cost-Math.min(x.discount,o.cost));if(x.coins<price||!x.dice[d]?.[f])return null;const dice=x.dice.map(y=>y.map(z=>({...z})));dice[d][f]={...o.face};return{...x,dice,coins:x.coins-price,discount:Math.max(0,x.discount-o.cost)};}
export function winner(p:Fighter,a:Fighter,n:number):"player"|"ai"|"tie"|null{if(p.health>0&&a.health>0&&n<=10)return null;const pv=p.health*100+p.shield+p.coins,av=a.health*100+a.shield+a.coins;return pv===av?"tie":pv>av?"player":"ai";}
export const newRound=(n:number,p:Fighter,a:Fighter,r:Rng):ForgeRound=>({number:n,playerRoll:rollDice(p.dice,r),aiRoll:rollDice(a.dice,r),locked:null,playerResult:null,aiResult:null,shop:createShop(r,n)});
